# Generated by Django 5.2.13 on 2026-08-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=300)),
                ('activity_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.CharField(max_length=20)),
                ('document_name', models.CharField(max_length=200)),
                ('document_hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('current_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DigiLocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='digilocker/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OriginalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=20, unique=True)),
                ('document_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='original_documents/')),
                ('sha256_hash', models.CharField(max_length=64)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.CharField(max_length=20, unique=True)),
                ('document_name', models.CharField(max_length=200)),
                ('generated_hash', models.CharField(max_length=64)),
                ('blockchain_hash', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=30)),
                ('verified_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
