# Generated by Django 5.2.13 on 2026-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originaldocument',
            old_name='category',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='originaldocument',
            old_name='document_file',
            new_name='uploaded_file',
        ),
        migrations.RemoveField(
            model_name='originaldocument',
            name='document_id',
        ),
        migrations.AddField(
            model_name='originaldocument',
            name='block_hash',
            field=models.CharField(default='GENESIS', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originaldocument',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='originaldocument',
            name='status',
            field=models.CharField(default='Verified', max_length=20),
        ),
    ]
