# Generated by Django 5.2.13 on 2026-08-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_category_originaldocument_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=50)),
                ('verified_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
