# Generated by Django 5.2.13 on 2026-08-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_category_digilocker_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digilocker',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
            preserve_default=False,
        ),
    ]
